import std/[os, osproc, strutils]

proc main() {.inline.} =
  let target = paramStr(1)
  let name = splitPath(target).tail
  let nimicName = name.multiReplace({"-": "_"}).changeFileExt(".nim")
  let finalDest = "src/nayland/bindings/protocols" / nimicName
  let finalPrivDest = "private-code/" & nimicName.changeFileExt(".c")
  let finalFullPrivDest = "src/nayland/bindings/protocols" / finalPrivDest

  assert execCmd("wayland-scanner client-header " & target & " /tmp/nayland-bindgen.h") ==
    0
  assert execCmd("wayland-scanner private-code " & target & ' ' & finalFullPrivDest) == 0
  assert execCmd(
    "c2nim --stdints --cdecl /tmp/nayland-bindgen.h --out:/tmp/nayland-bindgen.nim"
  ) == 0

  var bindingCode = readFile("/tmp/nayland-bindgen.nim")
  bindingCode = bindingCode.multiReplace(
    {
      "wayland-client": "pkg/nayland/bindings/libwayland",
      "*: wl_interface": "* {.importc.}: wl_interface",
      "cast[proc () {.cdecl.}]": "cast[ptr proc() {.cdecl.}]",
    }
  )

  var finalBuffer = newStringOfCap(bindingCode.len + 128)
  finalBuffer &= "## Generated by nayland-bindgen. Do not edit!\n"
  finalBuffer &= "import pkg/nayland/bindings/protocols/core\n"

  finalBuffer &= "\n# Link private code for protocol\n"
  finalBuffer &= "{.compile(\"" & finalPrivDest & "\", core.LibwaylandCflags).}\n\n"

  for line in splitLines(bindingCode):
    var line = line
    const ForwardDeclOutput = "discard \"forward decl of "

    if line.contains(ForwardDeclOutput):
      let typName = line.split(ForwardDeclOutput)[1].strip(
        leading = false, trailing = true, chars = {'"'}
      )
      if not typName.startsWith("wl_"):
        # We don't want to declare these, as libwayland.nim takes care of em.
        line = "type " & typName & "* = object"

    finalBuffer &= ensureMove(line)
    finalBuffer &= '\n'

  writeFile(finalDest, ensureMove(finalBuffer))

  let nphPath = findExe("nph")
  if nphPath.len > 0:
    discard execCmd(nphPath & ' ' & finalDest)

when isMainModule:
  main()
